### ISSUE TITLE
Busca por filtro por nome do estabelecimento

### ISSUE THREAD

**Issue by mauriciomelo** [simpatize/simpatize_webservice#3]
EU COMO  usuário

QUERO  buscar um estabelecimento pelo nome

PARA  visualizar os detalhes/avaliações e/ou recomendar um local

 

O WebService deve disponibilizar uma API REST com o Endpoint "/places".

Quando uma chamada HTTP GET for feita ao webservice com a URL "http://endereco:porta/places", este deve retornar uma lista de todos os Estabelecimentos (Places) de Recife. 

Atualmente, o Simpatize só disponibiliza estabelecimentos de Recife. 

Referência para desenvolvimento: Django Rest Tutorial http://www.django-rest-framework.org/tutorial/quickstart/

 

 

CONTEXTO DO NEGÓCIO
 
 

O usuário poderá realizar uma recomendação ou consultar a avaliação de estabelecimentos por causas friendly's. Para isso, poderá precisar realizar uma busca pelo nome do estabelecimento.

 
Notas
Os usuários são representados por pessoas pertencentes a minorias sociais

!FullSizeRender__1_.jpg!

Fora do escopo
NA

 
CRITÉRIOS DE ACEITE
 
1. Busca por um estabelecimento existente
DADO que estou na tela de busca

QUANDO eu buscar pelo nome de um estabelecimento existente

ENTÃO eu devo visualizar o nome do estabelecimento na lista de resultados

 

2. Busca por um estabelecimento inexistente
             DADO que estou na tela de busca

QUANDO eu buscar pelo nome de um estabelecimento inexistente

ENTÃO eu devo visualizar a mensagem: "Estabelecimento não encontrado".

 

3. Consulta à URL quando existem estabelecimentos cadastrados 
              DADO que existam estabelecimentos cadastrados que respondam ao filtro (nome) passado

QUANDO eu fizer uma requisição do tipo GET para a URL http://endereco:porta/places?name=<valor>

ENTÃO uma lista com todos os estabelecimentos daquele filtro em Recife deve ser retornada.

 

4. Consulta à URL quando não existem estabelecimentos cadastrados 
             DADO que não existam estabelecimentos cadastrados que respondam ao filtro (nome) passado

QUANDO eu fizer uma requisição do tipo GET para a URL http://endereco:porta/places?name=<valor>

ENTÃO uma lista vazia deve ser retornada.

**Comment by ffmmjj** [comment]
Marcada como duplicada devido à issue simpatize/simpatize_webservice#7
